title: gambaterm
email: vxgmichel@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Playing Game Boy Color Games in your Terminal
github_username: vxgmichel
repository: vxgmichel/gambatte-terminal

# Build settings
theme: jekyll-theme-cayman
kramdown:
  parse_block_html: true