/* Minimal config.h for libsixel encoder -- not generated by autotools.
 * Provides the HAVE_* defines required by the encoder source files.
 */

/* Standard C89/C99 headers */
#define HAVE_ASSERT_H 1
#define HAVE_CTYPE_H 1
#define HAVE_ERRNO_H 1
#define HAVE_FCNTL_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MATH_H 1
#define HAVE_MEMORY_H 1
#define HAVE_SETJMP_H 1
#define HAVE_STDARG_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_TIME_H 1
#define HAVE_UNISTD_H 1

/* POSIX headers */
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_TERMIOS_H 1

/* Functions */
#define HAVE_ISATTY 1
#define HAVE_LDIV 1
#define HAVE_LONGJMP 1
#define HAVE_MEMCPY 1
#define HAVE_NANOSLEEP 1
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_SETJMP 1
#define HAVE_CLEARERR 1
#define HAVE_CLOCK 1
#define HAVE_STAT 1

/* Compiler features */
#define HAVE_DIAGNOSTIC_DEPRECATED_DECLARATIONS 0
#define HAVE_DIAGNOSTIC_SIGN_CONVERSION 0
#define HAVE_DIAGNOSTIC_STRICT_OVERFLOW 0
#define HAVE_DIAGNOSTIC_SWITCH_DEFAULT 0
#define HAVE_DIAGNOSTIC_SHADOW 0
#define HAVE_DIAGNOSTIC_DOUBLE_PROMOTION 0
#define HAVE_DIAGNOSTIC_UNUSED_BUT_SET_VARIABLE 0
#define HAVE_DIAGNOSTIC_UNUSED_FUNCTION 0
#define HAVE_DIAGNOSTIC_CLOBBERED 0
#define HAVE_DIAGNOSTIC_UNINITIALIZED 0
#define HAVE_DIAGNOSTIC_TYPEDEF_REDEFINITION 0

/* Optional features -- not available (omit define to use #ifdef guards) */
