# This file is generated by `scripts/dom_code.py` using the DOM code data from:
# https://chromium.googlesource.com/chromium/src/+/main/ui/events/keycodes/dom/dom_code_data.inc

from __future__ import annotations

from enum import Enum
from dataclasses import dataclass

_USB_SCANCODE_TO_DOM_CODE: dict[int, DomCode] = {}
_EVDEV_SCANCODE_TO_DOM_CODE: dict[int, DomCode] = {}
_XKB_SCANCODE_TO_DOM_CODE: dict[int, DomCode] = {}
_WIN_SCANCODE_TO_DOM_CODE: dict[int, DomCode] = {}
_MAC_SCANCODE_TO_DOM_CODE: dict[int, DomCode] = {}


@dataclass(frozen=True)
class Scancodes:
    usb: int
    evdev: int
    xkb: int
    win: int
    mac: int


class DomCode(Enum):
    HYPER = "Hyper"
    SUPER = "Super"
    FN_LOCK = "FnLock"
    SUSPEND = "Suspend"
    RESUME = "Resume"
    TURBO = "Turbo"
    SLEEP = "Sleep"
    WAKE_UP = "WakeUp"
    FN = "Fn"
    DISPLAY_TOGGLE_INT_EXT = "DisplayToggleIntExt"
    US_A = "KeyA"
    US_B = "KeyB"
    US_C = "KeyC"
    US_D = "KeyD"
    US_E = "KeyE"
    US_F = "KeyF"
    US_G = "KeyG"
    US_H = "KeyH"
    US_I = "KeyI"
    US_J = "KeyJ"
    US_K = "KeyK"
    US_L = "KeyL"
    US_M = "KeyM"
    US_N = "KeyN"
    US_O = "KeyO"
    US_P = "KeyP"
    US_Q = "KeyQ"
    US_R = "KeyR"
    US_S = "KeyS"
    US_T = "KeyT"
    US_U = "KeyU"
    US_V = "KeyV"
    US_W = "KeyW"
    US_X = "KeyX"
    US_Y = "KeyY"
    US_Z = "KeyZ"
    DIGIT1 = "Digit1"
    DIGIT2 = "Digit2"
    DIGIT3 = "Digit3"
    DIGIT4 = "Digit4"
    DIGIT5 = "Digit5"
    DIGIT6 = "Digit6"
    DIGIT7 = "Digit7"
    DIGIT8 = "Digit8"
    DIGIT9 = "Digit9"
    DIGIT0 = "Digit0"
    ENTER = "Enter"
    ESCAPE = "Escape"
    BACKSPACE = "Backspace"
    TAB = "Tab"
    SPACE = "Space"
    MINUS = "Minus"
    EQUAL = "Equal"
    BRACKET_LEFT = "BracketLeft"
    BRACKET_RIGHT = "BracketRight"
    BACKSLASH = "Backslash"
    SEMICOLON = "Semicolon"
    QUOTE = "Quote"
    BACKQUOTE = "Backquote"
    COMMA = "Comma"
    PERIOD = "Period"
    SLASH = "Slash"
    CAPS_LOCK = "CapsLock"
    F1 = "F1"
    F2 = "F2"
    F3 = "F3"
    F4 = "F4"
    F5 = "F5"
    F6 = "F6"
    F7 = "F7"
    F8 = "F8"
    F9 = "F9"
    F10 = "F10"
    F11 = "F11"
    F12 = "F12"
    PRINT_SCREEN = "PrintScreen"
    SCROLL_LOCK = "ScrollLock"
    PAUSE = "Pause"
    INSERT = "Insert"
    HOME = "Home"
    PAGE_UP = "PageUp"
    DEL = "Delete"
    END = "End"
    PAGE_DOWN = "PageDown"
    ARROW_RIGHT = "ArrowRight"
    ARROW_LEFT = "ArrowLeft"
    ARROW_DOWN = "ArrowDown"
    ARROW_UP = "ArrowUp"
    NUM_LOCK = "NumLock"
    NUMPAD_DIVIDE = "NumpadDivide"
    NUMPAD_MULTIPLY = "NumpadMultiply"
    NUMPAD_SUBTRACT = "NumpadSubtract"
    NUMPAD_ADD = "NumpadAdd"
    NUMPAD_ENTER = "NumpadEnter"
    NUMPAD1 = "Numpad1"
    NUMPAD2 = "Numpad2"
    NUMPAD3 = "Numpad3"
    NUMPAD4 = "Numpad4"
    NUMPAD5 = "Numpad5"
    NUMPAD6 = "Numpad6"
    NUMPAD7 = "Numpad7"
    NUMPAD8 = "Numpad8"
    NUMPAD9 = "Numpad9"
    NUMPAD0 = "Numpad0"
    NUMPAD_DECIMAL = "NumpadDecimal"
    INTL_BACKSLASH = "IntlBackslash"
    CONTEXT_MENU = "ContextMenu"
    POWER = "Power"
    NUMPAD_EQUAL = "NumpadEqual"
    F13 = "F13"
    F14 = "F14"
    F15 = "F15"
    F16 = "F16"
    F17 = "F17"
    F18 = "F18"
    F19 = "F19"
    F20 = "F20"
    F21 = "F21"
    F22 = "F22"
    F23 = "F23"
    F24 = "F24"
    OPEN = "Open"
    HELP = "Help"
    SELECT = "Select"
    AGAIN = "Again"
    UNDO = "Undo"
    CUT = "Cut"
    COPY = "Copy"
    PASTE = "Paste"
    FIND = "Find"
    VOLUME_MUTE = "AudioVolumeMute"
    VOLUME_UP = "AudioVolumeUp"
    VOLUME_DOWN = "AudioVolumeDown"
    NUMPAD_COMMA = "NumpadComma"
    INTL_RO = "IntlRo"
    KANA_MODE = "KanaMode"
    INTL_YEN = "IntlYen"
    CONVERT = "Convert"
    NON_CONVERT = "NonConvert"
    LANG1 = "Lang1"
    LANG2 = "Lang2"
    LANG3 = "Lang3"
    LANG4 = "Lang4"
    LANG5 = "Lang5"
    ABORT = "Abort"
    PROPS = "Props"
    NUMPAD_PAREN_LEFT = "NumpadParenLeft"
    NUMPAD_PAREN_RIGHT = "NumpadParenRight"
    NUMPAD_BACKSPACE = "NumpadBackspace"
    NUMPAD_MEMORY_STORE = "NumpadMemoryStore"
    NUMPAD_MEMORY_RECALL = "NumpadMemoryRecall"
    NUMPAD_MEMORY_CLEAR = "NumpadMemoryClear"
    NUMPAD_MEMORY_ADD = "NumpadMemoryAdd"
    NUMPAD_MEMORY_SUBTRACT = "NumpadMemorySubtract"
    NUMPAD_CLEAR = "NumpadClear"
    NUMPAD_CLEAR_ENTRY = "NumpadClearEntry"
    CONTROL_LEFT = "ControlLeft"
    SHIFT_LEFT = "ShiftLeft"
    ALT_LEFT = "AltLeft"
    META_LEFT = "MetaLeft"
    CONTROL_RIGHT = "ControlRight"
    SHIFT_RIGHT = "ShiftRight"
    ALT_RIGHT = "AltRight"
    META_RIGHT = "MetaRight"
    BRIGHTNESS_UP = "BrightnessUp"
    BRIGHTNESS_DOWN = "BrightnessDown"
    MEDIA_PLAY = "MediaPlay"
    MEDIA_PAUSE = "MediaPause"
    MEDIA_RECORD = "MediaRecord"
    MEDIA_FAST_FORWARD = "MediaFastForward"
    MEDIA_REWIND = "MediaRewind"
    MEDIA_TRACK_NEXT = "MediaTrackNext"
    MEDIA_TRACK_PREVIOUS = "MediaTrackPrevious"
    MEDIA_STOP = "MediaStop"
    EJECT = "Eject"
    MEDIA_PLAY_PAUSE = "MediaPlayPause"
    MEDIA_SELECT = "MediaSelect"
    LAUNCH_MAIL = "LaunchMail"
    LAUNCH_APP2 = "LaunchApp2"
    LAUNCH_APP1 = "LaunchApp1"
    LAUNCH_CONTROL_PANEL = "LaunchControlPanel"
    SELECT_TASK = "SelectTask"
    LAUNCH_SCREEN_SAVER = "LaunchScreenSaver"
    LAUNCH_ASSISTANT = "LaunchAssistant"
    BROWSER_SEARCH = "BrowserSearch"
    BROWSER_HOME = "BrowserHome"
    BROWSER_BACK = "BrowserBack"
    BROWSER_FORWARD = "BrowserForward"
    BROWSER_STOP = "BrowserStop"
    BROWSER_REFRESH = "BrowserRefresh"
    BROWSER_FAVORITES = "BrowserFavorites"
    ZOOM_TOGGLE = "ZoomToggle"
    MAIL_REPLY = "MailReply"
    MAIL_FORWARD = "MailForward"
    MAIL_SEND = "MailSend"
    KEYBOARD_LAYOUT_SELECT = "KeyboardLayoutSelect"
    SHOW_ALL_WINDOWS = "ShowAllWindows"

    @property
    def scancodes(self) -> Scancodes:
        return DOM_CODE_TO_SCANCODES[self]

    @classmethod
    def from_usb_scancode(cls, code: int) -> DomCode | None:
        if code == 0x000000:
            return None
        if not _USB_SCANCODE_TO_DOM_CODE:
            for dom_code, scancodes in DOM_CODE_TO_SCANCODES.items():
                _USB_SCANCODE_TO_DOM_CODE[scancodes.usb] = dom_code
        return _USB_SCANCODE_TO_DOM_CODE.get(code)

    @classmethod
    def from_evdev_scancode(cls, code: int) -> DomCode | None:
        if code == 0x0000:
            return None
        if not _EVDEV_SCANCODE_TO_DOM_CODE:
            for dom_code, scancodes in DOM_CODE_TO_SCANCODES.items():
                _EVDEV_SCANCODE_TO_DOM_CODE[scancodes.evdev] = dom_code
        return _EVDEV_SCANCODE_TO_DOM_CODE.get(code)

    @classmethod
    def from_xkb_scancode(cls, code: int) -> DomCode | None:
        if code == 0x0000:
            return None
        if not _XKB_SCANCODE_TO_DOM_CODE:
            for dom_code, scancodes in DOM_CODE_TO_SCANCODES.items():
                _XKB_SCANCODE_TO_DOM_CODE[scancodes.xkb] = dom_code
        return _XKB_SCANCODE_TO_DOM_CODE.get(code)

    @classmethod
    def from_win_scancode(cls, code: int) -> DomCode | None:
        if code == 0x0000:
            return None
        if not _WIN_SCANCODE_TO_DOM_CODE:
            for dom_code, scancodes in DOM_CODE_TO_SCANCODES.items():
                _WIN_SCANCODE_TO_DOM_CODE[scancodes.win] = dom_code
        return _WIN_SCANCODE_TO_DOM_CODE.get(code)

    @classmethod
    def from_mac_scancode(cls, code: int) -> DomCode | None:
        if code == 0xFFFF:
            return None
        if not _MAC_SCANCODE_TO_DOM_CODE:
            for dom_code, scancodes in DOM_CODE_TO_SCANCODES.items():
                _MAC_SCANCODE_TO_DOM_CODE[scancodes.mac] = dom_code
        return _MAC_SCANCODE_TO_DOM_CODE.get(code)


DOM_CODE_TO_SCANCODES = {
    DomCode.HYPER: Scancodes(0x000010, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.SUPER: Scancodes(0x000011, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.FN_LOCK: Scancodes(0x000013, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.SUSPEND: Scancodes(0x000014, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.RESUME: Scancodes(0x000015, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.TURBO: Scancodes(0x000016, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.SLEEP: Scancodes(0x010082, 0x008E, 0x0096, 0xE05F, 0xFFFF),
    DomCode.WAKE_UP: Scancodes(0x010083, 0x008F, 0x0097, 0xE063, 0xFFFF),
    DomCode.FN: Scancodes(0x010097, 0x01D0, 0x01D8, 0x0000, 0xFFFF),
    DomCode.DISPLAY_TOGGLE_INT_EXT: Scancodes(0x0100B5, 0x00E3, 0x00EB, 0x0000, 0xFFFF),
    DomCode.US_A: Scancodes(0x070004, 0x001E, 0x0026, 0x001E, 0x0000),
    DomCode.US_B: Scancodes(0x070005, 0x0030, 0x0038, 0x0030, 0x000B),
    DomCode.US_C: Scancodes(0x070006, 0x002E, 0x0036, 0x002E, 0x0008),
    DomCode.US_D: Scancodes(0x070007, 0x0020, 0x0028, 0x0020, 0x0002),
    DomCode.US_E: Scancodes(0x070008, 0x0012, 0x001A, 0x0012, 0x000E),
    DomCode.US_F: Scancodes(0x070009, 0x0021, 0x0029, 0x0021, 0x0003),
    DomCode.US_G: Scancodes(0x07000A, 0x0022, 0x002A, 0x0022, 0x0005),
    DomCode.US_H: Scancodes(0x07000B, 0x0023, 0x002B, 0x0023, 0x0004),
    DomCode.US_I: Scancodes(0x07000C, 0x0017, 0x001F, 0x0017, 0x0022),
    DomCode.US_J: Scancodes(0x07000D, 0x0024, 0x002C, 0x0024, 0x0026),
    DomCode.US_K: Scancodes(0x07000E, 0x0025, 0x002D, 0x0025, 0x0028),
    DomCode.US_L: Scancodes(0x07000F, 0x0026, 0x002E, 0x0026, 0x0025),
    DomCode.US_M: Scancodes(0x070010, 0x0032, 0x003A, 0x0032, 0x002E),
    DomCode.US_N: Scancodes(0x070011, 0x0031, 0x0039, 0x0031, 0x002D),
    DomCode.US_O: Scancodes(0x070012, 0x0018, 0x0020, 0x0018, 0x001F),
    DomCode.US_P: Scancodes(0x070013, 0x0019, 0x0021, 0x0019, 0x0023),
    DomCode.US_Q: Scancodes(0x070014, 0x0010, 0x0018, 0x0010, 0x000C),
    DomCode.US_R: Scancodes(0x070015, 0x0013, 0x001B, 0x0013, 0x000F),
    DomCode.US_S: Scancodes(0x070016, 0x001F, 0x0027, 0x001F, 0x0001),
    DomCode.US_T: Scancodes(0x070017, 0x0014, 0x001C, 0x0014, 0x0011),
    DomCode.US_U: Scancodes(0x070018, 0x0016, 0x001E, 0x0016, 0x0020),
    DomCode.US_V: Scancodes(0x070019, 0x002F, 0x0037, 0x002F, 0x0009),
    DomCode.US_W: Scancodes(0x07001A, 0x0011, 0x0019, 0x0011, 0x000D),
    DomCode.US_X: Scancodes(0x07001B, 0x002D, 0x0035, 0x002D, 0x0007),
    DomCode.US_Y: Scancodes(0x07001C, 0x0015, 0x001D, 0x0015, 0x0010),
    DomCode.US_Z: Scancodes(0x07001D, 0x002C, 0x0034, 0x002C, 0x0006),
    DomCode.DIGIT1: Scancodes(0x07001E, 0x0002, 0x000A, 0x0002, 0x0012),
    DomCode.DIGIT2: Scancodes(0x07001F, 0x0003, 0x000B, 0x0003, 0x0013),
    DomCode.DIGIT3: Scancodes(0x070020, 0x0004, 0x000C, 0x0004, 0x0014),
    DomCode.DIGIT4: Scancodes(0x070021, 0x0005, 0x000D, 0x0005, 0x0015),
    DomCode.DIGIT5: Scancodes(0x070022, 0x0006, 0x000E, 0x0006, 0x0017),
    DomCode.DIGIT6: Scancodes(0x070023, 0x0007, 0x000F, 0x0007, 0x0016),
    DomCode.DIGIT7: Scancodes(0x070024, 0x0008, 0x0010, 0x0008, 0x001A),
    DomCode.DIGIT8: Scancodes(0x070025, 0x0009, 0x0011, 0x0009, 0x001C),
    DomCode.DIGIT9: Scancodes(0x070026, 0x000A, 0x0012, 0x000A, 0x0019),
    DomCode.DIGIT0: Scancodes(0x070027, 0x000B, 0x0013, 0x000B, 0x001D),
    DomCode.ENTER: Scancodes(0x070028, 0x001C, 0x0024, 0x001C, 0x0024),
    DomCode.ESCAPE: Scancodes(0x070029, 0x0001, 0x0009, 0x0001, 0x0035),
    DomCode.BACKSPACE: Scancodes(0x07002A, 0x000E, 0x0016, 0x000E, 0x0033),
    DomCode.TAB: Scancodes(0x07002B, 0x000F, 0x0017, 0x000F, 0x0030),
    DomCode.SPACE: Scancodes(0x07002C, 0x0039, 0x0041, 0x0039, 0x0031),
    DomCode.MINUS: Scancodes(0x07002D, 0x000C, 0x0014, 0x000C, 0x001B),
    DomCode.EQUAL: Scancodes(0x07002E, 0x000D, 0x0015, 0x000D, 0x0018),
    DomCode.BRACKET_LEFT: Scancodes(0x07002F, 0x001A, 0x0022, 0x001A, 0x0021),
    DomCode.BRACKET_RIGHT: Scancodes(0x070030, 0x001B, 0x0023, 0x001B, 0x001E),
    DomCode.BACKSLASH: Scancodes(0x070031, 0x002B, 0x0033, 0x002B, 0x002A),
    DomCode.SEMICOLON: Scancodes(0x070033, 0x0027, 0x002F, 0x0027, 0x0029),
    DomCode.QUOTE: Scancodes(0x070034, 0x0028, 0x0030, 0x0028, 0x0027),
    DomCode.BACKQUOTE: Scancodes(0x070035, 0x0029, 0x0031, 0x0029, 0x0032),
    DomCode.COMMA: Scancodes(0x070036, 0x0033, 0x003B, 0x0033, 0x002B),
    DomCode.PERIOD: Scancodes(0x070037, 0x0034, 0x003C, 0x0034, 0x002F),
    DomCode.SLASH: Scancodes(0x070038, 0x0035, 0x003D, 0x0035, 0x002C),
    DomCode.CAPS_LOCK: Scancodes(0x070039, 0x003A, 0x0042, 0x003A, 0x0039),
    DomCode.F1: Scancodes(0x07003A, 0x003B, 0x0043, 0x003B, 0x007A),
    DomCode.F2: Scancodes(0x07003B, 0x003C, 0x0044, 0x003C, 0x0078),
    DomCode.F3: Scancodes(0x07003C, 0x003D, 0x0045, 0x003D, 0x0063),
    DomCode.F4: Scancodes(0x07003D, 0x003E, 0x0046, 0x003E, 0x0076),
    DomCode.F5: Scancodes(0x07003E, 0x003F, 0x0047, 0x003F, 0x0060),
    DomCode.F6: Scancodes(0x07003F, 0x0040, 0x0048, 0x0040, 0x0061),
    DomCode.F7: Scancodes(0x070040, 0x0041, 0x0049, 0x0041, 0x0062),
    DomCode.F8: Scancodes(0x070041, 0x0042, 0x004A, 0x0042, 0x0064),
    DomCode.F9: Scancodes(0x070042, 0x0043, 0x004B, 0x0043, 0x0065),
    DomCode.F10: Scancodes(0x070043, 0x0044, 0x004C, 0x0044, 0x006D),
    DomCode.F11: Scancodes(0x070044, 0x0057, 0x005F, 0x0057, 0x0067),
    DomCode.F12: Scancodes(0x070045, 0x0058, 0x0060, 0x0058, 0x006F),
    DomCode.PRINT_SCREEN: Scancodes(0x070046, 0x0063, 0x006B, 0xE037, 0xFFFF),
    DomCode.SCROLL_LOCK: Scancodes(0x070047, 0x0046, 0x004E, 0x0046, 0xFFFF),
    DomCode.PAUSE: Scancodes(0x070048, 0x0077, 0x007F, 0x0045, 0xFFFF),
    DomCode.INSERT: Scancodes(0x070049, 0x006E, 0x0076, 0xE052, 0x0072),
    DomCode.HOME: Scancodes(0x07004A, 0x0066, 0x006E, 0xE047, 0x0073),
    DomCode.PAGE_UP: Scancodes(0x07004B, 0x0068, 0x0070, 0xE049, 0x0074),
    DomCode.DEL: Scancodes(0x07004C, 0x006F, 0x0077, 0xE053, 0x0075),
    DomCode.END: Scancodes(0x07004D, 0x006B, 0x0073, 0xE04F, 0x0077),
    DomCode.PAGE_DOWN: Scancodes(0x07004E, 0x006D, 0x0075, 0xE051, 0x0079),
    DomCode.ARROW_RIGHT: Scancodes(0x07004F, 0x006A, 0x0072, 0xE04D, 0x007C),
    DomCode.ARROW_LEFT: Scancodes(0x070050, 0x0069, 0x0071, 0xE04B, 0x007B),
    DomCode.ARROW_DOWN: Scancodes(0x070051, 0x006C, 0x0074, 0xE050, 0x007D),
    DomCode.ARROW_UP: Scancodes(0x070052, 0x0067, 0x006F, 0xE048, 0x007E),
    DomCode.NUM_LOCK: Scancodes(0x070053, 0x0045, 0x004D, 0xE045, 0x0047),
    DomCode.NUMPAD_DIVIDE: Scancodes(0x070054, 0x0062, 0x006A, 0xE035, 0x004B),
    DomCode.NUMPAD_MULTIPLY: Scancodes(0x070055, 0x0037, 0x003F, 0x0037, 0x0043),
    DomCode.NUMPAD_SUBTRACT: Scancodes(0x070056, 0x004A, 0x0052, 0x004A, 0x004E),
    DomCode.NUMPAD_ADD: Scancodes(0x070057, 0x004E, 0x0056, 0x004E, 0x0045),
    DomCode.NUMPAD_ENTER: Scancodes(0x070058, 0x0060, 0x0068, 0xE01C, 0x004C),
    DomCode.NUMPAD1: Scancodes(0x070059, 0x004F, 0x0057, 0x004F, 0x0053),
    DomCode.NUMPAD2: Scancodes(0x07005A, 0x0050, 0x0058, 0x0050, 0x0054),
    DomCode.NUMPAD3: Scancodes(0x07005B, 0x0051, 0x0059, 0x0051, 0x0055),
    DomCode.NUMPAD4: Scancodes(0x07005C, 0x004B, 0x0053, 0x004B, 0x0056),
    DomCode.NUMPAD5: Scancodes(0x07005D, 0x004C, 0x0054, 0x004C, 0x0057),
    DomCode.NUMPAD6: Scancodes(0x07005E, 0x004D, 0x0055, 0x004D, 0x0058),
    DomCode.NUMPAD7: Scancodes(0x07005F, 0x0047, 0x004F, 0x0047, 0x0059),
    DomCode.NUMPAD8: Scancodes(0x070060, 0x0048, 0x0050, 0x0048, 0x005B),
    DomCode.NUMPAD9: Scancodes(0x070061, 0x0049, 0x0051, 0x0049, 0x005C),
    DomCode.NUMPAD0: Scancodes(0x070062, 0x0052, 0x005A, 0x0052, 0x0052),
    DomCode.NUMPAD_DECIMAL: Scancodes(0x070063, 0x0053, 0x005B, 0x0053, 0x0041),
    DomCode.INTL_BACKSLASH: Scancodes(0x070064, 0x0056, 0x005E, 0x0056, 0x000A),
    DomCode.CONTEXT_MENU: Scancodes(0x070065, 0x007F, 0x0087, 0xE05D, 0x006E),
    DomCode.POWER: Scancodes(0x070066, 0x0074, 0x007C, 0xE05E, 0xFFFF),
    DomCode.NUMPAD_EQUAL: Scancodes(0x070067, 0x0075, 0x007D, 0x0059, 0x0051),
    DomCode.F13: Scancodes(0x070068, 0x00B7, 0x00BF, 0x0064, 0x0069),
    DomCode.F14: Scancodes(0x070069, 0x00B8, 0x00C0, 0x0065, 0x006B),
    DomCode.F15: Scancodes(0x07006A, 0x00B9, 0x00C1, 0x0066, 0x0071),
    DomCode.F16: Scancodes(0x07006B, 0x00BA, 0x00C2, 0x0067, 0x006A),
    DomCode.F17: Scancodes(0x07006C, 0x00BB, 0x00C3, 0x0068, 0x0040),
    DomCode.F18: Scancodes(0x07006D, 0x00BC, 0x00C4, 0x0069, 0x004F),
    DomCode.F19: Scancodes(0x07006E, 0x00BD, 0x00C5, 0x006A, 0x0050),
    DomCode.F20: Scancodes(0x07006F, 0x00BE, 0x00C6, 0x006B, 0x005A),
    DomCode.F21: Scancodes(0x070070, 0x00BF, 0x00C7, 0x006C, 0xFFFF),
    DomCode.F22: Scancodes(0x070071, 0x00C0, 0x00C8, 0x006D, 0xFFFF),
    DomCode.F23: Scancodes(0x070072, 0x00C1, 0x00C9, 0x006E, 0xFFFF),
    DomCode.F24: Scancodes(0x070073, 0x00C2, 0x00CA, 0x0076, 0xFFFF),
    DomCode.OPEN: Scancodes(0x070074, 0x0086, 0x008E, 0x0000, 0xFFFF),
    DomCode.HELP: Scancodes(0x070075, 0x008A, 0x0092, 0xE03B, 0xFFFF),
    DomCode.SELECT: Scancodes(0x070077, 0x0084, 0x008C, 0x0000, 0xFFFF),
    DomCode.AGAIN: Scancodes(0x070079, 0x0081, 0x0089, 0x0000, 0xFFFF),
    DomCode.UNDO: Scancodes(0x07007A, 0x0083, 0x008B, 0xE008, 0xFFFF),
    DomCode.CUT: Scancodes(0x07007B, 0x0089, 0x0091, 0xE017, 0xFFFF),
    DomCode.COPY: Scancodes(0x07007C, 0x0085, 0x008D, 0xE018, 0xFFFF),
    DomCode.PASTE: Scancodes(0x07007D, 0x0087, 0x008F, 0xE00A, 0xFFFF),
    DomCode.FIND: Scancodes(0x07007E, 0x0088, 0x0090, 0x0000, 0xFFFF),
    DomCode.VOLUME_MUTE: Scancodes(0x07007F, 0x0071, 0x0079, 0xE020, 0x004A),
    DomCode.VOLUME_UP: Scancodes(0x070080, 0x0073, 0x007B, 0xE030, 0x0048),
    DomCode.VOLUME_DOWN: Scancodes(0x070081, 0x0072, 0x007A, 0xE02E, 0x0049),
    DomCode.NUMPAD_COMMA: Scancodes(0x070085, 0x0079, 0x0081, 0x007E, 0x005F),
    DomCode.INTL_RO: Scancodes(0x070087, 0x0059, 0x0061, 0x0073, 0x005E),
    DomCode.KANA_MODE: Scancodes(0x070088, 0x005D, 0x0065, 0x0070, 0xFFFF),
    DomCode.INTL_YEN: Scancodes(0x070089, 0x007C, 0x0084, 0x007D, 0x005D),
    DomCode.CONVERT: Scancodes(0x07008A, 0x005C, 0x0064, 0x0079, 0xFFFF),
    DomCode.NON_CONVERT: Scancodes(0x07008B, 0x005E, 0x0066, 0x007B, 0xFFFF),
    DomCode.LANG1: Scancodes(0x070090, 0x007A, 0x0082, 0x0072, 0x0068),
    DomCode.LANG2: Scancodes(0x070091, 0x007B, 0x0083, 0x0071, 0x0066),
    DomCode.LANG3: Scancodes(0x070092, 0x005A, 0x0062, 0x0078, 0xFFFF),
    DomCode.LANG4: Scancodes(0x070093, 0x005B, 0x0063, 0x0077, 0xFFFF),
    DomCode.LANG5: Scancodes(0x070094, 0x0055, 0x005D, 0x0000, 0xFFFF),
    DomCode.ABORT: Scancodes(0x07009B, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.PROPS: Scancodes(0x0700A3, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.NUMPAD_PAREN_LEFT: Scancodes(0x0700B6, 0x00B3, 0x00BB, 0x0000, 0xFFFF),
    DomCode.NUMPAD_PAREN_RIGHT: Scancodes(0x0700B7, 0x00B4, 0x00BC, 0x0000, 0xFFFF),
    DomCode.NUMPAD_BACKSPACE: Scancodes(0x0700BB, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.NUMPAD_MEMORY_STORE: Scancodes(0x0700D0, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.NUMPAD_MEMORY_RECALL: Scancodes(0x0700D1, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.NUMPAD_MEMORY_CLEAR: Scancodes(0x0700D2, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.NUMPAD_MEMORY_ADD: Scancodes(0x0700D3, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.NUMPAD_MEMORY_SUBTRACT: Scancodes(0x0700D4, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.NUMPAD_CLEAR: Scancodes(0x0700D8, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.NUMPAD_CLEAR_ENTRY: Scancodes(0x0700D9, 0x0000, 0x0000, 0x0000, 0xFFFF),
    DomCode.CONTROL_LEFT: Scancodes(0x0700E0, 0x001D, 0x0025, 0x001D, 0x003B),
    DomCode.SHIFT_LEFT: Scancodes(0x0700E1, 0x002A, 0x0032, 0x002A, 0x0038),
    DomCode.ALT_LEFT: Scancodes(0x0700E2, 0x0038, 0x0040, 0x0038, 0x003A),
    DomCode.META_LEFT: Scancodes(0x0700E3, 0x007D, 0x0085, 0xE05B, 0x0037),
    DomCode.CONTROL_RIGHT: Scancodes(0x0700E4, 0x0061, 0x0069, 0xE01D, 0x003E),
    DomCode.SHIFT_RIGHT: Scancodes(0x0700E5, 0x0036, 0x003E, 0x0036, 0x003C),
    DomCode.ALT_RIGHT: Scancodes(0x0700E6, 0x0064, 0x006C, 0xE038, 0x003D),
    DomCode.META_RIGHT: Scancodes(0x0700E7, 0x007E, 0x0086, 0xE05C, 0x0036),
    DomCode.BRIGHTNESS_UP: Scancodes(0x0C006F, 0x00E1, 0x00E9, 0x0000, 0xFFFF),
    DomCode.BRIGHTNESS_DOWN: Scancodes(0x0C0070, 0x00E0, 0x00E8, 0x0000, 0xFFFF),
    DomCode.MEDIA_PLAY: Scancodes(0x0C00B0, 0x00CF, 0x00D7, 0x0000, 0xFFFF),
    DomCode.MEDIA_PAUSE: Scancodes(0x0C00B1, 0x00C9, 0x00D1, 0x0000, 0xFFFF),
    DomCode.MEDIA_RECORD: Scancodes(0x0C00B2, 0x00A7, 0x00AF, 0x0000, 0xFFFF),
    DomCode.MEDIA_FAST_FORWARD: Scancodes(0x0C00B3, 0x00D0, 0x00D8, 0x0000, 0xFFFF),
    DomCode.MEDIA_REWIND: Scancodes(0x0C00B4, 0x00A8, 0x00B0, 0x0000, 0xFFFF),
    DomCode.MEDIA_TRACK_NEXT: Scancodes(0x0C00B5, 0x00A3, 0x00AB, 0xE019, 0xFFFF),
    DomCode.MEDIA_TRACK_PREVIOUS: Scancodes(0x0C00B6, 0x00A5, 0x00AD, 0xE010, 0xFFFF),
    DomCode.MEDIA_STOP: Scancodes(0x0C00B7, 0x00A6, 0x00AE, 0xE024, 0xFFFF),
    DomCode.EJECT: Scancodes(0x0C00B8, 0x00A1, 0x00A9, 0xE02C, 0xFFFF),
    DomCode.MEDIA_PLAY_PAUSE: Scancodes(0x0C00CD, 0x00A4, 0x00AC, 0xE022, 0xFFFF),
    DomCode.MEDIA_SELECT: Scancodes(0x0C0183, 0x00AB, 0x00B3, 0xE06D, 0xFFFF),
    DomCode.LAUNCH_MAIL: Scancodes(0x0C018A, 0x009B, 0x00A3, 0xE06C, 0xFFFF),
    DomCode.LAUNCH_APP2: Scancodes(0x0C0192, 0x008C, 0x0094, 0xE021, 0xFFFF),
    DomCode.LAUNCH_APP1: Scancodes(0x0C0194, 0x0090, 0x0098, 0xE06B, 0xFFFF),
    DomCode.LAUNCH_CONTROL_PANEL: Scancodes(0x0C019F, 0x0243, 0x024B, 0x0000, 0xFFFF),
    DomCode.SELECT_TASK: Scancodes(0x0C01A2, 0x0244, 0x024C, 0x0000, 0xFFFF),
    DomCode.LAUNCH_SCREEN_SAVER: Scancodes(0x0C01B1, 0x0245, 0x024D, 0x0000, 0xFFFF),
    DomCode.LAUNCH_ASSISTANT: Scancodes(0x0C01CB, 0x0247, 0x024F, 0x0000, 0xFFFF),
    DomCode.BROWSER_SEARCH: Scancodes(0x0C0221, 0x00D9, 0x00E1, 0xE065, 0xFFFF),
    DomCode.BROWSER_HOME: Scancodes(0x0C0223, 0x00AC, 0x00B4, 0xE032, 0xFFFF),
    DomCode.BROWSER_BACK: Scancodes(0x0C0224, 0x009E, 0x00A6, 0xE06A, 0xFFFF),
    DomCode.BROWSER_FORWARD: Scancodes(0x0C0225, 0x009F, 0x00A7, 0xE069, 0xFFFF),
    DomCode.BROWSER_STOP: Scancodes(0x0C0226, 0x0080, 0x0088, 0xE068, 0xFFFF),
    DomCode.BROWSER_REFRESH: Scancodes(0x0C0227, 0x00AD, 0x00B5, 0xE067, 0xFFFF),
    DomCode.BROWSER_FAVORITES: Scancodes(0x0C022A, 0x009C, 0x00A4, 0xE066, 0xFFFF),
    DomCode.ZOOM_TOGGLE: Scancodes(0x0C0232, 0x0174, 0x017C, 0x0000, 0xFFFF),
    DomCode.MAIL_REPLY: Scancodes(0x0C0289, 0x00E8, 0x00F0, 0x0000, 0xFFFF),
    DomCode.MAIL_FORWARD: Scancodes(0x0C028B, 0x00E9, 0x00F1, 0x0000, 0xFFFF),
    DomCode.MAIL_SEND: Scancodes(0x0C028C, 0x00E7, 0x00EF, 0x0000, 0xFFFF),
    DomCode.KEYBOARD_LAYOUT_SELECT: Scancodes(0x0C029D, 0x0248, 0x0250, 0x0000, 0xFFFF),
    DomCode.SHOW_ALL_WINDOWS: Scancodes(0x0C029F, 0x0078, 0x0080, 0x0000, 0xFFFF),
}
