from enum import IntFlag
import numpy as np
import numpy.typing as npt

class GB:
    class LoadFlag(IntFlag):
        CGB_MODE = ...
        GBA_FLAG = ...
        RESERVED_FLAG = ...
        SGB_MODE = ...
        READONLY_SAV = ...
        NO_BIOS = ...
    def load(self, rom_file: str, flags: int = 0) -> int: ...
    def run_for(
        self,
        video: npt.NDArray[np.uint32],
        pitch: int,
        audio: npt.NDArray[np.int16],
        samples: int,
    ) -> tuple[int, int]: ...
    def set_input(self, value: int) -> None: ...
    def set_save_directory(self, path: str) -> None: ...
    def current_state(self) -> int: ...
    def select_state(self, state: int) -> None: ...
    def load_state(self) -> bool: ...
    def save_state(self, video: npt.NDArray[np.uint32] | None, pitch: int) -> bool: ...
