import base64
from urllib.request import urlopen
from dataclasses import dataclass

URL = "https://chromium.googlesource.com/chromium/src/+/main/ui/events/keycodes/dom/dom_code_data.inc"


@dataclass
class DomCode:
    name: str
    code: str
    usb: str
    evdev: str
    xkb: str
    win: str
    mac: str


def main() -> None:
    # Fetch the data from the URL
    with urlopen(f"{URL}?format=TEXT") as response:
        data = base64.b64decode(response.read()).decode("utf-8")

    # Remove comments, empty lines and line feeds
    lines: list[str] = []
    for line in data.splitlines():
        line = line.split("//", maxsplit=1)[0].strip()
        if not line:
            continue
        lines.append(line)
    data = "".join(lines)

    # Extract the data from the DOM_CODE macros
    dom_codes: list[DomCode] = []
    for line in data.split("),")[1:-1]:
        empty, data = line.split("DOM_CODE(", maxsplit=1)
        assert not empty
        usb, evdev, xkb, win, mac, code, name = map(str.strip, data.split(","))
        if code == "NULL":
            continue
        usb = f"0x{int(usb, 16):06X}"
        evdev = f"0x{int(evdev, 16):04X}"
        xkb = f"0x{int(xkb, 16):04X}"
        win = f"0x{int(win, 16):04X}"
        mac = f"0x{int(mac, 16):04X}"
        dom_codes.append(DomCode(name, code, usb, evdev, xkb, win, mac))

    # Generate the Python code
    print(
        f"# This file is generated by `scripts/dom_code.py` using the DOM code data from:\n# {URL}\n"
    )
    print(
        """\
from __future__ import annotations

from enum import Enum
from dataclasses import dataclass

_USB_SCANCODE_TO_DOM_CODE: dict[int, DomCode] = {}
_EVDEV_SCANCODE_TO_DOM_CODE: dict[int, DomCode] = {}
_XKB_SCANCODE_TO_DOM_CODE: dict[int, DomCode] = {}
_WIN_SCANCODE_TO_DOM_CODE: dict[int, DomCode] = {}
_MAC_SCANCODE_TO_DOM_CODE: dict[int, DomCode] = {}


@dataclass(frozen=True)
class Scancodes:
    usb: int
    evdev: int
    xkb: int
    win: int
    mac: int


class DomCode(Enum):\
"""
    )
    for dom_code in dom_codes:
        print(f"    {dom_code.name} = {dom_code.code}")
    print(
        """\

    @property
    def scancodes(self) -> Scancodes:
        return DOM_CODE_TO_SCANCODES[self]
"""
    )

    for code_name, none_value in [
        ("usb", "0x000000"),
        ("evdev", "0x0000"),
        ("xkb", "0x0000"),
        ("win", "0x0000"),
        ("mac", "0xFFFF"),
    ]:
        print(
            f"""\
    @classmethod
    def from_{code_name}_scancode(cls, code: int) -> DomCode | None:
        if code == {none_value}:
            return None
        if not _{code_name.upper()}_SCANCODE_TO_DOM_CODE:
            for dom_code, scancodes in DOM_CODE_TO_SCANCODES.items():
                _{code_name.upper()}_SCANCODE_TO_DOM_CODE[scancodes.{code_name}] = dom_code
        return _{code_name.upper()}_SCANCODE_TO_DOM_CODE.get(code)
"""
        )

    print(
        """\

DOM_CODE_TO_SCANCODES = {\
"""
    )
    for dom_code in dom_codes:
        print(
            f"    DomCode.{dom_code.name}: Scancodes({dom_code.usb}, {dom_code.evdev}, {dom_code.xkb}, {dom_code.win}, {dom_code.mac}),"
        )
    print("}")


if __name__ == "__main__":
    main()
